# name: Playwright Trading Tests with Allure

# on:
#   workflow_dispatch:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   trading:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         type: [unauthorized, authorized, unregistered]

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 20.18.0

#       - name: Install dependencies
#         run: npm ci

#       - name: Install Playwright browsers
#         run: npx playwright install --with-deps

#       - name: Clean previous allure results
#         run: rm -rf allure-results

#       - name: Run selected Trading tests
#         run: |
#           npx playwright test \
#             tests/trading_page/knock_outs_page.spec.js \
#             tests/trading_page/trading_view_page.spec.js \
#             tests/trading_page/cfd_trading_page.spec.js \
#             tests/trading_page/demo_trading_page.spec.js \
#             tests/trading_page/pro_account_page.spec.js \
#             --project=${{ matrix.type }} \
#             --reporter=list,allure-playwright \
#             --retries=2
#         continue-on-error: true

#       - name: Generate Allure report
#         if: always()
#         run: |
#           DATE=$(date +'%Y-%m-%d')
#           mkdir -p report/${{ matrix.type }}/$DATE
#           npx allure generate allure-results \
#             -o report/${{ matrix.type }}/$DATE

#       - name: Upload report artifact
#         if: always()
#         uses: actions/upload-artifact@v4
#         with:
#           name: report-${{ matrix.type }}
#           path: report/

#   deploy:
#     needs: trading
#     runs-on: ubuntu-latest
#     if: always()

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Checkout gh-pages
#         uses: actions/checkout@v4
#         continue-on-error: true
#         with:
#           ref: gh-pages
#           path: gh-pages

#       - name: Restore previous reports
#         run: |
#           mkdir -p allure-report
#           cp -R gh-pages/* allure-report/ || true

#       - name: Download all artifacts
#         uses: actions/download-artifact@v4
#         with:
#           path: downloaded

#       - name: Debug downloaded structure
#         run: find downloaded

#       - name: Merge reports
#         run: |
#           mkdir -p allure-report/Trading
#           cp -R downloaded/report-authorized/* allure-report/Trading/ || true
#           cp -R downloaded/report-unauthorized/* allure-report/Trading/ || true
#           cp -R downloaded/report-unregistered/* allure-report/Trading/ || true

#       - name: Deploy to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v4
#         with:
#           github_token: ${{ secrets.GH_PAT }}
#           publish_dir: ./allure-report
#           publish_branch: gh-pages
#           keep_files: true
